In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use("ggplot")

In [2]:
data = pd.read_csv("ner_dataset.csv", encoding="latin1")
data = data.drop(['POS'], axis =1)
data = data.fillna(method="ffill")
data.tail(12)

              Sentence #       Word    Tag
1048563  Sentence: 47958   exploded      O
1048564  Sentence: 47958       upon      O
1048565  Sentence: 47958     impact      O
1048566  Sentence: 47958          .      O
1048567  Sentence: 47959     Indian  B-gpe
1048568  Sentence: 47959     forces      O
1048569  Sentence: 47959       said      O
1048570  Sentence: 47959       they      O
1048571  Sentence: 47959  responded      O
1048572  Sentence: 47959         to      O
1048573  Sentence: 47959        the      O
1048574  Sentence: 47959     attack      O